{{- if .Values.prometheus.enabled }}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: slimstack
    app.kubernetes.io/component: slimstack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Values.prometheus.server.clusterRoleName }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - nodes/metrics
      - services
      - endpoints
      - pods
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups:
      - "metrics.eks.amazonaws.com"
    resources:
      - ksh/metrics
      - kcm/metrics
    verbs:
      - get
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: slimstack
    app.kubernetes.io/component: slimstack
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Values.prometheus.server.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceAccounts.server.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.server.clusterRoleName }}
{{- end }}