{{- if .Values.auth.createSecret }}
{{- $auth_token := .Values.auth.token | required ".Values.auth.token is required." -}}
{{- $secretName := "" }}
{{- range .Values.prometheus.server.extraSecretMounts }}
  {{- if eq .name "auth-file" }}
    {{- $secretName = .secretName }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  token: {{ .Values.auth.token }}
{{- end }}
