{{- if .Values.mutator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mutator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mutator.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{ if .Values.mutator.wandControl -}}
    wand.cloud/workload-is-controlled: "true"
    {{- end }}
spec:
  replicas: {{ .Values.mutator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "mutator.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "mutator.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "mutator.fullname" . }}
                topologyKey: "kubernetes.io/hostname"
      serviceAccountName: {{ template "mutator.fullname" . }}
      containers:
        - name: {{ template "mutator.fullname" . }}
          image: {{ include "mutator.image" . }}
          imagePullPolicy: {{ .Values.mutator.image.pullPolicy }}
          env:
            - name: "DEBUG"
              value: "{{ .Values.mutator.debugLog }}"
            - name: "CONFIG_NAMESPACE"
              value: "{{ .Release.Namespace }}"
            - name: "MUTATE_BY_DEFAULT"
              value: "{{ .Values.mutator.mutateByDefault }}"
            - name: "CUSTOMER_ID"
              value: "{{ include "customerID" . }}"
            - name: "CLUSTER_ID"
              value: "{{ include "clusterID" . }}"
            {{- range $key, $value := .Values.mutator.extraEnvVars }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          ports:
            - containerPort: 443
          {{- if .Values.mutator.resources }}
          resources:
          {{- .Values.mutator.resources | toYaml | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readiness
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
{{- end }}
