{{- if and .Values.mutator.enabled .Values.mutator.pdb.enabled }}
{{- if ge (int .Values.mutator.replicas) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mutator.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "mutator.fullname" . }}
{{- end }}
{{- end }}