{{- if and .Values.controller.enabled .Values.controller.mutator.pdb.enabled }}
{{- if ge (int .Values.controller.mutator.replicas) 2 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mutator.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "mutator.fullname" . }}
{{- end }}
{{- end }}