{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mutator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "mutator.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "mutator.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: 8443
      targetPort: 443
    - name: metrics
      port: 8080
      targetPort: 8080
{{- end }}
