{{- if .Values.controller.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ .Values.controller.mutator.name }}
webhooks:
  - name: mutator.slimstack.io
    clientConfig:
      service:
        name: {{ .Values.controller.mutator.name }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURiVENDQWxXZ0F3SUJBZ0lVUWExNGRCRGpveGJmNFpkU05hWHF3RndDS0drd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1NURUxNQWtHQTFVRUJoTUNTVXd4RHpBTkJnTlZCQWdNQmtsemNtRmxiREVTTUJBR0ExVUVDZ3dKVTJ4cApiWE4wWVdOck1SVXdFd1lEVlFRRERBeHpiR2x0YzNSaFkyc3VhVzh3SGhjTk1qTXdPREUxTVRJeE5EVXdXaGNOCk1qUXdPREUwTVRJeE5EVXdXakJKTVFzd0NRWURWUVFHRXdKSlRERVBNQTBHQTFVRUNBd0dTWE55WVdWc01SSXcKRUFZRFZRUUtEQWxUYkdsdGMzUmhZMnN4RlRBVEJnTlZCQU1NREhOc2FXMXpkR0ZqYXk1cGJ6Q0NBU0l3RFFZSgpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFKNjhWb1duODROVjhnajNUSHNQVVZ4NVdlQXZCYmZKCjBFZ0VtblFNU1BJUDFMZWxNbXRieUpzRkdJVkt1eTlJNHhob3NKYmU1ZWt6bmIydjdybXNQNEJaWXoxMTZTMk4KaGxBV1ZGcTRoK0VjU05lVC94ZklIRUlGRWRCUnMxdDFhVk1LVVRtOVZDb25aMy94T202cThoYnVPR1JFRVhicAp1SWJyY3owWk4ySnZqUVcxNXNFdSt3dE1JMnlLR05USGIxMXFWcE1FMFZIdEVRdGxiWUhnVnRSU3ExWWxqT0pNClhkbnU0TGxwN3NKZWxTNG0rOGVpM3ZRUDhoOWFMUnEveGNMc3kxTWZkRmFSNTE0RU9UZklPbHlMU21yVGxIOHQKbmFOSmd1aURDbUZYZ0J3Ym5POStURXJvRDcrTmtrNHljaEpHNUVRbjdNNUFpbnNsa2kyMlliVUNBd0VBQWFOTgpNRXN3S2dZRFZSMFJCQ013SVlJZmMyeHBiWE4wWVdOckxXMTFkR0YwYjNJdWMyeHBiWE4wWVdOckxuTjJZekFkCkJnTlZIUTRFRmdRVVhLZmNyUWd0cVFCN1paaVVSejZwNEh1eUxNc3dEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUIKQUYxbUZwS1h2Ry9oakFXR0haNU5TMGd0MjlRYzJXbmlvRVZBSC9CeGV0bXNMdzdMbWZETkFtazJYTlFFMGhpRAo5TDdyRDZPTmZ3WVduR2hVUHN4eVNoeVFBS0djaWM1b1dBNXB3dXc5MVZXRkVmL00zTU5CcWJML3BQZVpmMVUwCmNGc3U0TFlwQ3I0STVzc1ZqbGFldy8yUllDLzBtNnMwU1Nma3J0aHlzcGgySEh0WFgzWmFVcDBCL3pLRmYyRFEKV3krOUFUdlNKRHAvbVp0dS9FRVZrRDJHRW9ROVZocWZHSjVUS3hLQlU0S0M3MXpudXRDYnAxZkVMa3pZaG8yOApWWXhOZEFqVzhNYm5ZSjlHSVZSN2VRMVZyTERCYVVrNGNzSHF6d2Y2Sm5MZXJ5Tkd1VnZlMTZ6NS9BRVJnN3lYCllrK1FHMTFwbzhVODAzUm1zc0ptNjVRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments", "statefulsets", "daemonsets"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["batch"]
        apiVersions: ["v1", "v1beta1"]
        resources: ["cronjobs"]
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1"]
{{- end }}
