{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controller.mutator.name }}
  labels:
    app: {{ .Values.controller.mutator.name }}
spec:
  selector:
    app: {{ .Values.controller.mutator.name }}
  ports:
    - name: https
      port: 443
      targetPort: 443
{{- end }}
