name: Build and Index Helm Chart

permissions:
  contents: write
  actions: write

on:
  push:
    branches:
      - main

jobs:
  build_and_index_chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Build & Index Helm Chart
        run: |
          helm dep up slimstack
          helm package slimstack
          helm repo index --url https://slimstackio.github.io/charts/ .

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Helm chart index" || echo "No changes to commit"
          git fetch --all
          git branch gh-pages || echo "gh-pages already exists"
          git push origin gh-pages