name: Build and Index Helm Chart

on:
  push:
    branches:
      - main

jobs:
  build_and_index_chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Build Helm Chart
        run: |
          # Replace this with the command to build your Helm chart
          helm package slimstack

      - name: Index Helm Chart
        run: |
          # Replace this with the command to index your Helm chart
          helm repo index slimstack

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Helm chart index"
          git push origin gh-pages